### PR TITLE
Build/update packages 2024 07 30

### PR DESCRIPTION
**Pull request by AyresMonteiro**
### This pull request is responsible for:

- Fixing dependencies (npm audit fix)
- Increasing package version in order to publish it correctly to npm

### CODE REVIEW

**Comment by AyresMonteiro** [comment]
Hi @greatSumini! Greetings!

I came to push build updates again. Would you mind reviewing this pull request? (And if possible, publishing the new version on npm)

Thanks!

**Comment by olucasmarquess** [comment]
Hi @greatSumini it's a great update. 

Please review and approve at your earliest convenience as this update is highly important. :v

**Comment by IcaroWeiler** [comment]
@greatSumini that's a good update, please review asap, thanks!

**Comment by AyresMonteiro** [comment]
Hi @greatSumini!

I would appreciate it if you took a look at this issue :)

**Pull request closed without merging**
