### PR TITLE
chore: update dependencies with npm audit fix and bump nestjs version to 10

### PR DESCRIPTION
**Pull request by AyresMonteiro**

### CODE REVIEW

**Comment by AyresMonteiro** [comment]
Hi @greatSumini, I want to bump the nestjs version of this package to 10 or at least the peer dependencies of nestjs to version 10. Please review my Pull Request, thanks!

**Comment by Luc-emanuel** [comment]
@AyresMonteiro Good idea, I hope it gets approved soon.

**Comment by bryannbarbosa** [comment]
it will be a great idea to configure this package for the new version of NestJS, good! @AyresMonteiro

**Comment by anton-brass** [comment]
is this going to happen? waiting for it , would be great :)

**Comment by erodrigues-developer** [comment]
Hello everyone.
Any update about this topic?

**Comment by erodrigues-developer** [comment]
@greatSumini

**Review by erodrigues-developer — APPROVED** [review]

**Pull request merged**
